name: Docker Image Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          registry: dreamhunter2333.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Rename AWSL_API_HOST
        run: echo VITE_API_HOSTNAME=${{ secrets.AWSL_API_HOST }} > .env.production

      - name: Install and Build
        run: npm i -g pnpm && pnpm i && pnpm build

      - name: Build the Docker image
        run: docker build . --file docker/Dockerfile --tag dreamhunter2333.azurecr.io/awsl/awsl-front:${{ steps.get_version.outputs.VERSION }}
      - name: Push the Docker image
        run: docker push dreamhunter2333.azurecr.io/awsl/awsl-front:${{ steps.get_version.outputs.VERSION }}
